package Project.controller;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class IndexController {

    @GetMapping("/")
    public ResponseEntity<String> index() {
        String html = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Task Automation System</title>\n"
                + "    <link rel=\"stylesheet\" href=\"/css/styles.css\">\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div class=\"container\">\n"
                + "        <header class=\"header\">\n"
                + "            <h1>Task Automation System</h1>\n"
                + "            <nav class=\"nav\">\n"
                + "                <div id=\"authNav\">\n"
                + "                    <button class=\"btn\" id=\"showLogin\">Login</button>\n"
                + "                    <button class=\"btn btn-secondary\" id=\"showRegister\">Register</button>\n"
                + "                </div>\n"
                + "                <div id=\"tasksNav\" class=\"hidden\">\n"
                + "                    <button class=\"btn\" id=\"showTasks\">My Tasks</button>\n"
                + "                    <button class=\"btn btn-secondary\" id=\"logoutBtn\">Logout</button>\n"
                + "                </div>\n"
                + "            </nav>\n"
                + "        </header>\n"
                + "\n"
                + "        <div id=\"userInfo\" class=\"user-info hidden\">\n"
                + "            <span>Welcome, <span id=\"currentUser\"></span>!</span>\n"
                + "        </div>\n"
                + "\n"
                + "        <section id=\"authSection\" class=\"section auth-section\">\n"
                + "            <h2>Authentication</h2>\n"
                + "\n"
                + "            <form id=\"loginForm\" class=\"auth-form\">\n"
                + "                <div class=\"form-group\">\n"
                + "                    <label for=\"loginUsername\">Username</label>\n"
                + "                    <input type=\"text\" id=\"loginUsername\" required>\n"
                + "                </div>\n"
                + "                <div class=\"form-group\">\n"
                + "                    <label for=\"loginPassword\">Password</label>\n"
                + "                    <input type=\"password\" id=\"loginPassword\" required>\n"
                + "                </div>\n"
                + "                <button type=\"submit\" class=\"btn\">Login</button>\n"
                + "            </form>\n"
                + "\n"
                + "            <form id=\"registerForm\" class=\"auth-form hidden\">\n"
                + "                <div class=\"form-group\">\n"
                + "                    <label for=\"registerUsername\">Username</label>\n"
                + "                    <input type=\"text\" id=\"registerUsername\" required>\n"
                + "                </div>\n"
                + "                <div class=\"form-group\">\n"
                + "                    <label for=\"registerEmail\">Email</label>\n"
                + "                    <input type=\"email\" id=\"registerEmail\" required>\n"
                + "                </div>\n"
                + "                <div class=\"form-group\">\n"
                + "                    <label for=\"registerPassword\">Password</label>\n"
                + "                    <input type=\"password\" id=\"registerPassword\" required minlength=\"6\">\n"
                + "                </div>\n"
                + "                <button type=\"submit\" class=\"btn\">Register</button>\n"
                + "            </form>\n"
                + "\n"
                + "            <div class=\"auth-links\">\n"
                + "                <a href=\"#\" id=\"showLoginLink\">Already have an account? Login</a> |\n"
                + "                <a href=\"#\" id=\"showRegisterLink\">Need an account? Register</a>\n"
                + "            </div>\n"
                + "        </section>\n"
                + "\n"
                + "        <section id=\"tasksSection\" class=\"section tasks-section hidden\">\n"
                + "            <h2>My Tasks</h2>\n"
                + "\n"
                + "            <div class=\"task-form\">\n"
                + "                <h3>Create New Task</h3>\n"
                + "                <form id=\"taskForm\">\n"
                + "                    <div class=\"form-row\">\n"
                + "                        <div class=\"form-group\">\n"
                + "                            <label for=\"taskTitle\">Title</label>\n"
                + "                            <input type=\"text\" id=\"taskTitle\" required>\n"
                + "                        </div>\n"
                + "                        <div class=\"form-group\">\n"
                + "                            <label for=\"taskDescription\">Description</label>\n"
                + "                            <input type=\"text\" id=\"taskDescription\">\n"
                + "                        </div>\n"
                + "                        <div class=\"form-group\">\n"
                + "                            <label for=\"taskDueDate\">Due Date</label>\n"
                + "                            <input type=\"date\" id=\"taskDueDate\">\n"
                + "                        </div>\n"
                + "                        <div class=\"form-group\">\n"
                + "                            <label for=\"taskPriority\">Priority</label>\n"
                + "                            <select id=\"taskPriority\">\n"
                + "                                <option value=\"LOW\">Low</option>\n"
                + "                                <option value=\"MEDIUM\" selected>Medium</option>\n"
                + "                                <option value=\"HIGH\">High</option>\n"
                + "                            </select>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <button type=\"submit\" class=\"btn\">Create Task</button>\n"
                + "                </form>\n"
                + "            </div>\n"
                + "\n"
                + "            <div id=\"taskList\" class=\"task-list\">\n"
                + "                <!-- Tasks will be loaded here -->\n"
                + "            </div>\n"
                + "        </section>\n"
                + "    </div>\n"
                + "\n"
                + "    <script src=\"/js/app.js\"></script>\n"
                + "</body>\n"
                + "</html>";
        return ResponseEntity.ok()
                .contentType(MediaType.TEXT_HTML)
                .body(html);
    }
}
